import Head from 'next/head';

import Manager from '@docker/components/Manager';

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Dashboard Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Manager />
    </>
  );
}
