import Head from 'next/head';

export default function Home() {
  return (
    <div className={'container'}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div>
          <h1>Boniche gang</h1>
        </div>
      </main>
    </div>
  );
}